### ISSUE TITLE
Nominal Readme Clarification

### ISSUE THREAD

**Issue by mmadson** [Coder-Spirit/nominal#103]
The installation instructions in the nominal README state to use npm install or yarn add --dev. The npm install instructions will add nominal as a production dependency whereas the yarn install instructions will add nominal as a dev dependency. This seems inconsistent. How should we install nominal? regular dependency or dev dependency specifically when the nominal branded types will be added to a library that will then be re-used by multiple downstream dependencies? 

Thanks and appreciate the great work on this incredibly useful library.

**Comment by castarco** [comment]
Hi @mmadson , thank you for reporting this inconsistency in the documentation.

As a general rule, `@coderspirit/nominal` should be installed as a development dependency... with some exceptions: if you are writing your own library and intend to expose types related to `@coderspirit/nominal`, then you have to set it as a normal dependency of said library.

I'll try to find some time to improve that explanation.

**Comment by mmadson** [comment]
Thanks so much for the clarification. This helps greatly as I was incorrectly using a dev dependency for my library. Will switch it to a regular dependency. Cheers!

**Comment by castarco** [comment]
Fixed in one of my last PRs.
